export const ImagePath={
    logo1:require('../assets/images/ArihantPlusLogo1.png'),
    otp:require('../assets/images/otpImage.png'),
    google:require('../assets/images/Google.png'),
    arrowLeft:require('../assets/images/arrow-left.png'),
    loginBackGround:require('../assets/images/LoginBackground.png'),
    Book:require('../assets/images/book.jpg'),
    replace:require('../assets/images/replacement.png'),
    cashondelivery:require('../assets/images/cashondelivery.png'),
    freeshipping:require('../assets/images/freeshipping.png'),
    securepayment:require('../assets/images/securepayment.png'),
    language:require('../assets/images/language.png'),
    publisher:require('../assets/images/publisher.png'),
    calender:require('../assets/images/calender.png'),
    heart:require('../assets/images/hearts.png'),
    share:require('../assets/images/share.png'),
    share2:require('../assets/images/share2.png'),
    introbackground:require('../assets/images/walkinbackground.png'),
    category1:require('../assets/images/category1.png'),
    category2:require('../assets/images/category2.png'),
    category3:require('../assets/images/category3.png'),
    category4:require('../assets/images/category4.png'),
    category5:require('../assets/images/category5.png'),
    category6:require('../assets/images/category6.png'),
    category7:require('../assets/images/category7.png'),
    courseicon:require('../assets/images/iconforcourse.png'),
    expert1:require('../assets/images/expert.png'),
    expert2:require('../assets/images/expert2.png'),
    topper:require('../assets/images/topper1.png'),
    sbn:require('../assets/images/isbn.png'),
    file:require('../assets/images/files.png'),
    page1:require('../assets/images/page1.png'),
    frqbook:require('../assets/images/frqbook.jpg'),
    excelExam1:require('../assets/images/excelExam1.png'),
    excelExam2:require('../assets/images/excelExam2.png'),
    excelExam3:require('../assets/images/excelExam3.png'),
    excelExamCircle:require('../assets/images/excelExamCircle.png'),
    commonBanner:require('../assets/images/commonBanner.png'),
    filter:require('../assets/images/filter.png'),
    list:require('../assets/images/List.png'),
    Cross:require('../assets/images/cross.png'),
    slideimage1:require('../assets/images/slideimage1.png'),
    slideimage2:require('../assets/images/slideimage2.png'),
    slideimage3:require('../assets/images/slideimage3.png'),
    mcat1:require("../assets/images/mcat1.png"),
    mcat2:require("../assets/images/mcat2.png"),
    mcat3:require("../assets/images/mcat3.png"),
    mcat4:require("../assets/images/mcat4.png"),
    mcat5:require("../assets/images/mcat5.png"),
    mcat6:require("../assets/images/mcat6.png"),
    mcat7:require("../assets/images/mcat7.png"),
    mcat8:require("../assets/images/mcat8.png"),
    mcat9:require("../assets/images/mcat9.png"),
    mcat10:require("../assets/images/mcat10.png"),
    mcat11:require("../assets/images/mcat11.png"),
    mcat12:require("../assets/images/mcat12.png"),
    mcat13:require("../assets/images/mcat13.png"),
    mcat14:require("../assets/images/mcat14.png"),
    mcat15:require("../assets/images/mcat15.png"),
    mcat16:require("../assets/images/mcat16.png"),
    mcat17:require("../assets/images/mcat17.png"),
    mcat18:require("../assets/images/mcat18.png"),
    bell:require("../assets/images/bell.png"),
    trophy:require("../assets/images/Trophy.png"),
    mock_test:require("../assets/images/mock_test.png"),
    courseImage:require("../assets/images/courseImage.png"),
    arrowup_right:require("../assets/images/arrowup_right.png"),
    play:require("../assets/images/play.png"),
    play2:require("../assets/images/play2.png"),
    newsletterImage:require("../assets/images/newsletterimage.png"),
    bigimage:require('../assets/images/Rectangle47.png'),
    TabBannertop:require('../assets/images/TabBannertop.png'),
    homepagetabImage:require('../assets/images/homepagetabImage.png'),
    profileTab:require('../assets/images/profileTab.png'),

   arr_left:require('../assets/images/arr_left.png'),
    arr_right:require('../assets/images/arr_right.png'),
    frontpage:require('../assets/images/Rectangle1.png'),
    backpage:require('../assets/images/Rectangle2.png'),
    quickpage:require('../assets/images/Group2.png'),
    scanner:require('../assets/images/scanner.png'),
    homeimage:require('../assets/images/homeimage.png'),
    debitcard:require('../assets/images/debitcard.png'),
    liveClass:require('../assets/images/liveClasses.png'),
    arihantlogo:require('../assets/images/SimpleLogo.png'),
    crackexamimage:require('../assets/images/crackExamimage.jpg'),
    girlemoji:require('../assets/images/girlemoji.png'),
    boyemoji:require('../assets/images/boyemoji.png'),
    banner1:require('../assets/images/banner1.png'),
    banner2:require('../assets/images/banner2.png'),
    longarrowright:require('../assets/images/arrowright.png'),
    RightArrow1:require('../assets/images/RightArrow1.png'),
    RightArrowSubscribe:require('../assets/images/RightArrowSubscribe.png'),
    toppergirl:require('../assets/images/toppergirl.png'),
    leftlongarrow:require('../assets/images/leftlongarrow.png'),
    testlist:require('../assets/images/testlist.png'),
    emojiarihant:require('../assets/images/emojiarihant.png'),
    starbackground:require('../assets/images/starbackground.png'),
    starbackground2:require('../assets/images/starbackground2.png'),
    practiceSetImage:require('../assets/images/practiceSetImage.png'),
    clocklist:require('../assets/images/clocklist.png'),
    listicon:require('../assets/images/Vector.png'),
    calender2:require('../assets/images/calender2.png'),
    livedot:require('../assets/images/livedot.png'),
    check:require('../assets/images/check.png'),
    clock:require('../assets/images/clock.png'),
    en:require('../assets/images/EN.png'),
    profile:require('../assets/images/profile.png'),
    background1:require('../assets/images/background1.png'),
    background2:require('../assets/images/background2.png'),
    listicon2:require('../assets/images/listicon2.png'),
    frame1:require('../assets/images/Frame1.png'),
    frame2:require('../assets/images/Frame2.png'),
    frame1image:require('../assets/images/frame1image.png'),
    frame2image:require('../assets/images/frame2image.png'),
    redPlayButon:require('../assets/images/redPlayButton.png'),
    RoundLogo:require('../assets/images/RoundLogo.png'),
    cardheadbg:require('../assets/images/cardheadbag.png'),
    percent:require('../assets/images/percent.png'),
    infinity:require('../assets/images/infinity.png'),
    enicon:require('../assets/images/enicon.png'),
    spark:require('../assets/images/spark.png'),
    analyticChart:require('../assets/images/analyticChart.png'),
    list3:require('../assets/images/list3.png'),
    mobileclick:require('../assets/images/mobileclick.png'),
    mobiebanner:require('../assets/images/bannermobile.png'),
    eye:require('../assets/images/eye.png'),
    videowithexpert:require('../assets/images/videowithexpert.png'),
    orangecircle:require('../assets/images/Orangecircle.png'),
    pdf:require('../assets/images/pdfImage.png'),
    downarrowforborder:require('../assets/images/downarrowforborder.png'),
    arrowDown:require('../assets/images/arrow-down.png'),
    upborder:require('../assets/images/uplineImage.png'),
    downborder:require('../assets/images/downlineImage.png'),
    thankyouemoji:require('../assets/images/thankyouemoji.png'),
    borderup:require('../assets/images/borderup.png'),
    trianglechart:require('../assets/images/trianglechart.png'),
    backgroundclrd:require('../assets/images/backgroundclrd.png'),
    grpofteacher:require('../assets/images/grpofteacher.png'),
    smallbackgroundclrd:require('../assets/images/smallbackgroundclrd.png'),
    teachermale:require('../assets/images/teachermale.png'),
    
    sidearrow:require('../assets/images/sidearrow.png'),
    rightsidelongarrow:require('../assets/images/rightsidelongarrow.png'),
    leftsidelongarrow:require('../assets/images/leftsidelongarrow.png'),
    rightarrow:require('../assets/images/rightarrow.png'),
    longarrowleft_side:require('../assets/images/longarrowleft_side.png'),
    longarrowright_side:require('../assets/images/longarrowright_side.png'),
    roundedsmallbackground:require('../assets/images/roundedsmallbackground.png'),
    teachermale2:require('../assets/images/teachermale2.png'),
    starback3:require('../assets/images/starback3.png'),
    ladyTeacher:require('../assets/images/ladyTeacher.png'),
    rectangle : require('../assets/images/rectangle.png'),
    searched : require('../assets/images/searched.png'),
    Bankingmam:require('../assets/images/Bankingmam.png'),
    logowithwhitebackground:require('../assets/images/logowithwhitebackground.png'),
    starofbanner:require('../assets/images/starforbanner.png'),
    Groupe : require('../assets/images/Groupe.png'),
    lang : require('../assets/images/lang.png'),
    markedNotAnswered:require('../assets/images/markNotAnswered.png'),
    explorebtn :require('../assets/images/explorebtn.png'),
    arrowimage1:require('../assets/images/arrowimage.png'),
    Animation1:require('../assets/images/Animation1.png'),
    Animation2:require('../assets/images/Animation2.png'),
    Animation3:require('../assets/images/Animation3.png'),
    playwithblackborder:require('../assets/images/playwithblackborder.png'),
    Arrow3:require('../assets/images/Arrow3.png'),
    Search:require('../assets/images/Search.png'),
    bag:require('../assets/images/bag.png'),
    cart:require('../assets/images/cart.png'),
    subscribeArrow:require('../assets/images/subscribeArrow.png'),
    blackandwhite:require('../assets/images/blackandwhite.png'),
    problemSolving:require('../assets/images/problemSolving.png'),
    examStrategy:require('../assets/images/examStrategy.png'),
    conceptClarity:require('../assets/images/conceptClarity.png'),
    doubtimg:require('../assets/images/doubtimg.png'),
    ebookicon:require('../assets/images/ebookicon.png'),
    testpackageicon:require('../assets/images/testpackageicon.png'),
    videopackageicon:require('../assets/images/videopackageicon.png'),
    cancelicon:require('../assets/images/cancelicon.png'),
    buyagainicon:require('../assets/images/buyagainicon.png'),
    magazinesicon:require('../assets/images/magazinesicon.png'),
    ordericon:require('../assets/images/ordericon.png'),
    grouppic:require('../assets/images/grouppic.png'),
    flag:require('../assets/images/flag.png'),
    ship:require('../assets/images/ship.png'),
    petrol:require('../assets/images/petrol.png'),
    gangster:require('../assets/images/gangster.png'),
    OmarAbdulla:require('../assets/images/OmarAbdulla.png'),
   blog1:require('../assets/images/blog1.png'),
    blog2:require('../assets/images/blog2.png'),
    blog3:require('../assets/images/blog3.png'),
    graylogo:require('../assets/images/graylogo.png'),
    contactus:require('../assets/images/contactus.png'),
    MailIcon:require('../assets/images/MailIcon.png'),
    ClockIcon:require('../assets/images/ClockIcon.png'),
    CallIcon:require('../assets/images/CallIcon.png'),
    serviceIcon1:require('../assets/images/serviceIcon1.png'),
    serviceIcon2:require('../assets/images/serviceIcon2.png'),
    serviceIcon3:require('../assets/images/serviceIcon3.png'),
    testpackage:require('../assets/images/testpackage.png'),
    videopackage:require('../assets/images/videopackage.png'),

















    




   


















     
}
